Basic AsyncSeq compatability
demystifyfp/FsToolkit.ErrorHandling pull request #138
Opened 2021-09-13 18:18 UTC by njlr

2021-09-13 18:59 UTC, TheAngryByrd commented
# Paket Lock Diff Report

This report was generated via [Paket Lock Diff](https://paket-lock-diff.azurewebsites.net/?olderLockFileUrl=https%3A%2F%2Fraw.githubusercontent.com%2Fdemystifyfp%2FFsToolkit.ErrorHandling%2Fmaster%2Fpaket.lock&newerLockFileUrl=https%3A%2F%2Fraw.githubusercontent.com%2Fdemystifyfp%2FFsToolkit.ErrorHandling%2Fb74e51fb673dd5a6af7afb58c653a49d53d10215%2Fpaket.lock)

## Additions - (88)

* Build - (10)
  * [Microsoft.Bcl.AsyncInterfaces - 5.0.0](https://www.fuget.org/packages/Microsoft.Bcl.AsyncInterfaces/5.0.0/)
  * [Microsoft.NET.StringTools - 1.0.0](https://www.fuget.org/packages/Microsoft.NET.StringTools/1.0.0/)
  * [Microsoft.Win32.SystemEvents - 5.0.0](https://www.fuget.org/packages/Microsoft.Win32.SystemEvents/5.0.0/)
  * [System.Configuration.ConfigurationManager - 5.0.0](https://www.fuget.org/packages/System.Configuration.ConfigurationManager/5.0.0/)
  * [System.Drawing.Common - 5.0.2](https://www.fuget.org/packages/System.Drawing.Common/5.0.2/)
  * [System.Security.Cryptography.Xml - 5.0.0](https://www.fuget.org/packages/System.Security.Cryptography.Xml/5.0.0/)
  * [System.Security.Permissions - 5.0.0](https://www.fuget.org/packages/System.Security.Permissions/5.0.0/)
  * [System.Text.Encodings.Web - 5.0.1](https://www.fuget.org/packages/System.Text.Encodings.Web/5.0.1/)
  * [System.Text.Json - 5.0.2](https://www.fuget.org/packages/System.Text.Json/5.0.2/)
  * [System.Windows.Extensions - 5.0.0](https://www.fuget.org/packages/System.Windows.Extensions/5.0.0/)

* Main - (2)
  * [FSharp.Control.AsyncSeq - 3.1.0](https://www.fuget.org/packages/FSharp.Control.AsyncSeq/3.1.0/)
  * [Microsoft.Bcl.AsyncInterfaces - 5.0.0](https://www.fuget.org/packages/Microsoft.Bcl.AsyncInterfaces/5.0.0/)

* Test - (76)
  * [Microsoft.NETCore.Platforms - 5.0.2](https://www.fuget.org/packages/Microsoft.NETCore.Platforms/5.0.2/)
  * [Microsoft.NETCore.Targets - 5.0.0](https://www.fuget.org/packages/Microsoft.NETCore.Targets/5.0.0/)
  * [Microsoft.NETFramework.ReferenceAssemblies.net35 - 1.0.2](https://www.fuget.org/packages/Microsoft.NETFramework.ReferenceAssemblies.net35/1.0.2/)
  * [runtime.debian.8-x64.runtime.native.System.Security.Cryptography.OpenSsl - 4.3.3](https://www.fuget.org/packages/runtime.debian.8-x64.runtime.native.System.Security.Cryptography.OpenSsl/4.3.3/)
  * [runtime.debian.9-x64.runtime.native.System.Security.Cryptography.OpenSsl - 4.3.3](https://www.fuget.org/packages/runtime.debian.9-x64.runtime.native.System.Security.Cryptography.OpenSsl/4.3.3/)
  * [runtime.fedora.23-x64.runtime.native.System.Security.Cryptography.OpenSsl - 4.3.3](https://www.fuget.org/packages/runtime.fedora.23-x64.runtime.native.System.Security.Cryptography.OpenSsl/4.3.3/)
  * [runtime.fedora.24-x64.runtime.native.System.Security.Cryptography.OpenSsl - 4.3.3](https://www.fuget.org/packages/runtime.fedora.24-x64.runtime.native.System.Security.Cryptography.OpenSsl/4.3.3/)
  * [runtime.fedora.27-x64.runtime.native.System.Security.Cryptography.OpenSsl - 4.3.3](https://www.fuget.org/packages/runtime.fedora.27-x64.runtime.native.System.Security.Cryptography.OpenSsl/4.3.3/)
  * [runtime.fedora.28-x64.runtime.native.System.Security.Cryptography.OpenSsl - 4.3.3](https://www.fuget.org/packages/runtime.fedora.28-x64.runtime.native.System.Security.Cryptography.OpenSsl/4.3.3/)
  * [runtime.native.System - 4.3.1](https://www.fuget.org/packages/runtime.native.System/4.3.1/)
  * [runtime.native.System.Net.Http - 4.3.1](https://www.fuget.org/packages/runtime.native.System.Net.Http/4.3.1/)
  * [runtime.native.System.Security.Cryptography.Apple - 4.3.1](https://www.fuget.org/packages/runtime.native.System.Security.Cryptography.Apple/4.3.1/)
  * [runtime.native.System.Security.Cryptography.OpenSsl - 4.3.3](https://www.fuget.org/packages/runtime.native.System.Security.Cryptography.OpenSsl/4.3.3/)
  * [runtime.opensuse.13.2-x64.runtime.native.System.Security.Cryptography.OpenSsl - 4.3.3](https://www.fuget.org/packages/runtime.opensuse.13.2-x64.runtime.native.System.Security.Cryptography.OpenSsl/4.3.3/)
  * [runtime.opensuse.42.1-x64.runtime.native.System.Security.Cryptography.OpenSsl - 4.3.3](https://www.fuget.org/packages/runtime.opensuse.42.1-x64.runtime.native.System.Security.Cryptography.OpenSsl/4.3.3/)
  * [runtime.opensuse.42.3-x64.runtime.native.System.Security.Cryptography.OpenSsl - 4.3.3](https://www.fuget.org/packages/runtime.opensuse.42.3-x64.runtime.native.System.Security.Cryptography.OpenSsl/4.3.3/)
  * [runtime.osx.10.10-x64.runtime.native.System.Security.Cryptography.Apple - 4.3.1](https://www.fuget.org/packages/runtime.osx.10.10-x64.runtime.native.System.Security.Cryptography.Apple/4.3.1/)
  * [runtime.osx.10.10-x64.runtime.native.System.Security.Cryptography.OpenSsl - 4.3.3](https://www.fuget.org/packages/runtime.osx.10.10-x64.runtime.native.System.Security.Cryptography.OpenSsl/4.3.3/)
  * [runtime.rhel.7-x64.runtime.native.System.Security.Cryptography.OpenSsl - 4.3.3](https://www.fuget.org/packages/runtime.rhel.7-x64.runtime.native.System.Security.Cryptography.OpenSsl/4.3.3/)
  * [runtime.ubuntu.14.04-x64.runtime.native.System.Security.Cryptography.OpenSsl - 4.3.3](https://www.fuget.org/packages/runtime.ubuntu.14.04-x64.runtime.native.System.Security.Cryptography.OpenSsl/4.3.3/)
  * [runtime.ubuntu.16.04-x64.runtime.native.System.Security.Cryptography.OpenSsl - 4.3.3](https://www.fuget.org/packages/runtime.ubuntu.16.04-x64.runtime.native.System.Security.Cryptography.OpenSsl/4.3.3/)
  * [runtime.ubuntu.16.10-x64.runtime.native.System.Security.Cryptography.OpenSsl - 4.3.3](https://www.fuget.org/packages/runtime.ubuntu.16.10-x64.runtime.native.System.Security.Cryptography.OpenSsl/4.3.3/)
  * [runtime.ubuntu.18.04-x64.runtime.native.System.Security.Cryptography.OpenSsl - 4.3.3](https://www.fuget.org/packages/runtime.ubuntu.18.04-x64.runtime.native.System.Security.Cryptography.OpenSsl/4.3.3/)
  * [System.AppContext - 4.3.0](https://www.fuget.org/packages/System.AppContext/4.3.0/)
  * [System.Buffers - 4.5.1](https://www.fuget.org/packages/System.Buffers/4.5.1/)
  * [System.Collections - 4.3.0](https://www.fuget.org/packages/System.Collections/4.3.0/)
  * [System.Collections.Concurrent - 4.3.0](https://www.fuget.org/packages/System.Collections.Concurrent/4.3.0/)
  * [System.Console - 4.3.1](https://www.fuget.org/packages/System.Console/4.3.1/)
  * [System.Diagnostics.Debug - 4.3.0](https://www.fuget.org/packages/System.Diagnostics.Debug/4.3.0/)
  * [System.Diagnostics.DiagnosticSource - 5.0.1](https://www.fuget.org/packages/System.Diagnostics.DiagnosticSource/5.0.1/)
  * [System.Diagnostics.Tools - 4.3.0](https://www.fuget.org/packages/System.Diagnostics.Tools/4.3.0/)
  * [System.Diagnostics.Tracing - 4.3.0](https://www.fuget.org/packages/System.Diagnostics.Tracing/4.3.0/)
  * [System.Globalization - 4.3.0](https://www.fuget.org/packages/System.Globalization/4.3.0/)
  * [System.Globalization.Calendars - 4.3.0](https://www.fuget.org/packages/System.Globalization.Calendars/4.3.0/)
  * [System.Globalization.Extensions - 4.3.0](https://www.fuget.org/packages/System.Globalization.Extensions/4.3.0/)
  * [System.IO - 4.3.0](https://www.fuget.org/packages/System.IO/4.3.0/)
  * [System.IO.FileSystem - 4.3.0](https://www.fuget.org/packages/System.IO.FileSystem/4.3.0/)
  * [System.IO.FileSystem.Primitives - 4.3.0](https://www.fuget.org/packages/System.IO.FileSystem.Primitives/4.3.0/)
  * [System.Linq - 4.3.0](https://www.fuget.org/packages/System.Linq/4.3.0/)
  * [System.Linq.Expressions - 4.3.0](https://www.fuget.org/packages/System.Linq.Expressions/4.3.0/)
  * [System.Linq.Queryable - 4.3.0](https://www.fuget.org/packages/System.Linq.Queryable/4.3.0/)
  * [System.Memory - 4.5.4](https://www.fuget.org/packages/System.Memory/4.5.4/)
  * [System.Net.Http - 4.3.4](https://www.fuget.org/packages/System.Net.Http/4.3.4/)
  * [System.Net.Primitives - 4.3.1](https://www.fuget.org/packages/System.Net.Primitives/4.3.1/)
  * [System.Net.Requests - 4.3.0](https://www.fuget.org/pa [...]

2021-09-13 19:07 UTC, TheAngryByrd requested changes
Looks mostly good to me! 


- I think we need to update the [package.json](https://github.com/demystifyfp/FsToolkit.ErrorHandling/blob/master/package.json#L8) test statements if we want to have it run the AsyncSeq tests under fable. I'm not sure what the change exactly looks like since I'm not a fable/javascript expert.

2021-09-13 19:25 UTC, njlr commented
Ah yes, I will update it to get Fable tests working since `FSharp.Control.AsyncSeq` is Fable compatible.

2021-10-14 18:25 UTC, njlr commented
I have added AsyncSeq to the Fable tests. 

However, they don't work quite yet, I think due to this: https://github.com/fsprojects/FSharp.Control.AsyncSeq/issues/145

So I think this is blocked until we figure that out

2021-11-07 17:41 UTC, TheAngryByrd commented
I think we're still waiting on https://github.com/fsprojects/FSharp.Control.AsyncSeq/pull/149 to be released to be able to merge this.

2021-11-08 22:15 UTC, njlr commented
Seems to work with latest `FSharp.Control.AsyncSeq`!

2021-11-08 23:37 UTC, TheAngryByrd requested changes
Would you mind rebasing from master instead of merging? This seems to add a bunch of duplicate commits from master.

2021-11-23 18:16 UTC, closed without merging