Add Async<'value voption> support to asyncOptionCE
demystifyfp/FsToolkit.ErrorHandling pull request #226
Opened 2023-08-04 23:26 UTC by Xyncgas

We can currently use ```let!``` to bind to either option or value option in ```option {}``` computation expression, I am making asyncOption to be able to do this too, it couldn't before I made it to.

it does so by converting your voption to option, which is how OptionCE does it
https://github.com/demystifyfp/FsToolkit.ErrorHandling/issues/225#issuecomment-1665588509

2023-08-05 02:10 UTC, TheAngryByrd requested changes
Thanks for this! Could you also add corresponding tests in the test suite? Tests for let! and return! should be sufficient.

2023-08-07 14:31 UTC, Xyncgas commented
Added tests

2023-08-07 14:54 UTC, TheAngryByrd requested changes

2023-08-07 14:54 UTC, TheAngryByrd commented on tests/FsToolkit.ErrorHandling.Tests/AsyncOptionCE.fs
> +        testCaseAsync "Return ValueSome Result"
```suggestion
        testCaseAsync "Return ValueSome AsyncOption"
```

2023-08-07 14:54 UTC, TheAngryByrd commented on tests/FsToolkit.ErrorHandling.Tests/AsyncOptionCE.fs
> +        testCaseAsync "Bind ValueSome Result"
```suggestion
        testCaseAsync "Bind ValueSome AsyncOption"
```

2024-12-21 20:42 UTC, closed without merging