Refactor AsyncValidationCE module for bugfix
demystifyfp/FsToolkit.ErrorHandling pull request #260
Opened 2024-04-03 22:19 UTC by 1eyewonder

## Proposed Changes

Refactored the AsyncValidationCE source overloads to fix the issue seen in the last Amplifying F# video where AsyncResults were not binding correctly

## Types of changes

What types of changes does your code introduce to FsToolkit.ErrorHandling?
_Put an `x` in the boxes that apply and remove ones that don't apply_ 

- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [X] Build and tests pass locally
- [X] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [ ] I have added necessary documentation (if appropriate)

## Further comments

⚠️ Please sanity check me. I think I updated a test case correctly, but because I am modifying a previous test case, I would appreciate a second set of eyes on this

2024-04-04 01:49 UTC, TheAngryByrd commented on tests/FsToolkit.ErrorHandling.Tests/AsyncValidationCE.fs
> +            let expected = Error [ [ innerData ] ]
This doesn't seem right. It shouldn't be a double list.

2024-05-02 02:27 UTC, 1eyewonder commented
@TheAngryByrd assuming build server works fine, I think this is good to look at again. I believe I fixed the issue mentioned above and noticed I didn't even include the task bindings initially. I went ahead and added those along with cleaning up some unnecessary `Result` namespace qualifiers. Let me know if you want anything done differently and sorry for such a long delay!

2024-05-02 15:28 UTC, TheAngryByrd requested changes
Thanks for fixing it up! Left some feedback.

2024-05-02 15:28 UTC, TheAngryByrd commented on tests/FsToolkit.ErrorHandling.Tests/AsyncValidationCE.fs
> +        testCaseAsync "Happy Path Async Result/Async Result"
Nit: These aren't really happy path if we're expecting errors 😄

2024-05-02 15:28 UTC, TheAngryByrd commented on tests/FsToolkit.ErrorHandling.Tests/AsyncValidationCE.fs
> +                            printfn "Hello"
```suggestion

```

2024-05-02 15:28 UTC, TheAngryByrd commented on tests/FsToolkit.ErrorHandling.Tests/AsyncValidationCE.fs
> +                            printfn "World"
```suggestion

```

2024-05-02 15:28 UTC, TheAngryByrd commented on tests/FsToolkit.ErrorHandling.Tests/AsyncValidationCE.fs
> +                            printfn "Hello"
```suggestion

```

2024-05-02 15:28 UTC, TheAngryByrd commented on tests/FsToolkit.ErrorHandling.Tests/AsyncValidationCE.fs
> +                            printfn "World"
```suggestion
```

2024-05-02 17:15 UTC, merged