Add Task.ignore
demystifyfp/FsToolkit.ErrorHandling pull request #272
Opened 2024-07-14 07:47 UTC by odytrice

## Proposed Changes

- Adds `Task.ignore` for situations like the following

```fsharp
let makePost = task {
  do! savePost createPostRequest |> Task.ignore
}
```

## Types of changes

What types of changes does your code introduce to FsToolkit.ErrorHandling?
_Put an `x` in the boxes that apply and remove ones that don't apply_ 

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] Build and tests pass locally
- [ ] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [x] I have added necessary documentation (if appropriate)

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

2024-07-14 19:00 UTC, bartelink commented on src/FsToolkit.ErrorHandling.TaskResult/Task.fs
> +    let inline ignore (x: Task<'a>) =
I'd go with copying
https://github.com/fsprojects/FSharp.Control.TaskSeq/blob/main/src/FSharp.Control.TaskSeq/Utils.fs#L45-L51

Abel would know the details as to exactly why...

2024-07-15 13:08 UTC, TheAngryByrd requested changes
Awesome, thanks for this. Just a small nitpick.

2024-07-15 13:08 UTC, TheAngryByrd commented on src/FsToolkit.ErrorHandling.TaskResult/Task.fs
> +    let inline ignore (x: Task<'a>) =
Add a doc comment for this based on the docs added.

2024-07-15 19:24 UTC, TheAngryByrd approved these changes

2024-07-15 19:30 UTC, merged

2025-03-05 07:03 UTC, bartelink commented
@TheAngryByrd IIRC this signature does not allow a `'T` to be specified
For me, being able to do `Async.Ignore<unit[]>` is valuable, and the equivalent for Task (to be able to make explicit and typesafe what it it that you are casting away) is important. Let me know if you'd take a breaking change for V5

https://github.com/jet/propulsion/blob/master/src/Propulsion/Internal.fs#L160

2025-03-05 15:04 UTC, TheAngryByrd commented
@bartelink I thought this got added in https://github.com/demystifyfp/FsToolkit.ErrorHandling/pull/300/

2025-03-05 15:19 UTC, bartelink commented
Wait, I'm asleep (not sure when I last tried), thanks for finding it!
Any thoughts/policy about having an `Async.ignore<'T>` (which would be a direct call to `Async.Ignore`) for symmetry ?

2025-03-05 17:53 UTC, TheAngryByrd commented
Yeah I think that makes sense.