Removed Async.retn since it duplicates Async.singleton
demystifyfp/FsToolkit.ErrorHandling pull request #287
Opened 2024-12-15 20:39 UTC by 1eyewonder

## Proposed Changes

Removed `Async.retn` since it was duplicating `Async.singleton`. This should simplify the API slightly. This addresses issue #267 

## Types of changes

What types of changes does your code introduce to FsToolkit.ErrorHandling?

- [X] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

- [X] Build and tests pass locally
- [ ] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [ ] I have added necessary documentation (if appropriate)

2024-12-17 14:45 UTC, TheAngryByrd requested changes
Thanks for this! 

1. You should be able to rebase from master this so it doesn't include all those extra commits.
2. Should we remove all the other `retn` functions? Seems weird to only pick on `Async` module.

2024-12-17 14:46 UTC, TheAngryByrd requested changes
Thanks for this! 

1. You should be able to rebase from master this so it doesn't include all those extra commits.
2. Should we remove all the other `retn` functions? Seems weird to only pick on `Async` module.

2024-12-17 18:04 UTC, 1eyewonder commented
So I converted all uses of `retn`, `ok`, and `some` into singleton since they all do the same thing. For the cases with a Result inside, there are still the `error` functions. For naming consistency with `map`, `bind`, etc. do we think naming it to `singletonError` makes sense or did I overreach by changing the `ok` and `some` functions?

2024-12-19 16:17 UTC, TheAngryByrd commented
I think keeping `some` and `ok` would be better than forcing everyone to convert to `singleton` and especially `error` and `none` to `singletonError`.

2024-12-19 18:16 UTC, 1eyewonder commented
Here are the current API changes so far. There may be some more massaging but hopefully this helps clarify the changes so far.

## IcedTasks API Changes

I'm guessing we may want to keep `ok` here to keep consistent with other validation-ish things

| Module                    | Notes                                    |
| ------------------------- | ---------------------------------------- |
| CancellableTaskValidation | Removed `ok`. Still contains `singleton` |

## JobResult API Changes

| Module          | Notes                           |
| --------------- | ------------------------------- |
| JobOption       | Converted `retn` to `singleton` |
| JobResult       | Converted `retn` to `singleton` |
| JobResultOption | Converted `retn` to `singleton` |

## Core Changes

For modules which contain both `singleton` & `some`/`ok` are we wanting to consolidate to just the latter?

| Module            | Notes                                               |
| ----------------- | --------------------------------------------------- |
| Async             | Removed `retn`. Still contains `singleton`          |
| AsyncOption       | Removed `retn`. Still contains `singleton` & `some` |
| AsyncResult       | Removed `retn`. Still contains `ok`                 |
| AsyncResultOption | Converted `retn` to `singleton`                     |
| AsyncValidation   | Removed `retn`. Still contains `ok`                 |
| ResultOption      | Converted `retn` to `singleton`                     |
| TaskOption        | Removed `retn`. Still contains `some`               |
| TaskResult        | Removed `retn`. Still contains `ok`                 |
| TaskResultOption  | Converted `retn` to `singleton`                     |
| Validation        | Removed `retn`. Still contains `ok`                 |

2024-12-21 18:35 UTC, TheAngryByrd approved these changes
This looks good! Thanks!

2024-12-21 18:35 UTC, merged